# Generated by Django 3.0.4 on 2020-04-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.IntegerField(default=7897),
            preserve_default=False,
        ),
    ]
